# Generated by Django 3.0.2 on 2020-02-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_project_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='volume',
            new_name='units',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
